### ISSUE TITLE
setprop类型错误

### ISSUE THREAD

**Issue by urain39** [urain39/KngetPyX#4]
`setprop`因为实现比较简单，缺少了类型转换在设置参数时容易造成类型错误。

解决方法：修改`knget.cmd_register`方法实现，通过`fmt`参数转换类型。

如`iis`表示3个参数，类型分别转换为`int, int, str`。

**Comment by 95e2** [comment]
最最最简单的解决方法：inifile模块里不在支持类型，由使用者自己实现。
